---
# tasks file for security-group-config
- name: Configure security group to allow ICMP
  os_security_group_rule:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ user }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      domain_name: "{{ domain_name }}"
    verify: false
    security_group: "{{ security_group }}"
    protocol: icmp
    remote_ip_prefix: "{{ remote_ip_prefix }}"

- name: Configure security group to allow SSH
  os_security_group_rule:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ user }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      domain_name: "{{ domain_name }}"
    verify: false
    security_group: "{{ security_group }}"
    port_range_min: 22
    port_range_max: 22
    protocol: tcp
    remote_ip_prefix: "{{ remote_ip_prefix }}"