---
# tasks file for flavor-create
- name: Create OSP Public Network
  os_network:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ user }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      domain_name: "{{ domain_name }}"
    verify: false
    state: present
    name: "{{ item.network_name }}"
    external: "{{ item.is_external }}"
    provider_physical_network: "{{ item.provider_physical_network }}"
    provider_network_type: "{{ item.provider_network_type }}"
    shared: "{{ item.is_shared }}"
  loop: "{{ networks }}"

- name: Create OSP Public Subnet
  os_subnet:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ user }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      domain_name: "{{ domain_name }}"
    verify: false
    state: present
    network_name: "{{ item.network_name }}"
    name: "{{ item.subnet_name }}"
    cidr: "{{ item.cidr}}"
    dns_nameservers: "{{ item.dns_nameservers }}"
    gateway_ip: "{{ item.gateway_ip }}"
    allocation_pool_start: "{{ item.allocation_pool_start }}"
    allocation_pool_end: "{{ item.allocation_pool_end }}"
  loop: "{{ networks }}"
